name: attendance
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - cmake
  - dlib
  - opencv
pip:
numpy
streamlit
streamlit-lottie
requests
pyttsx3
pandas
face-recognition
